//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 14.05.2017 21:10:52
namespace MainWindow.WcfDataServiceReference
{
    
    /// <summary>
    /// There are no comments for FamilyEconomicEntities in the schema.
    /// </summary>
    public partial class FamilyEconomicEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new FamilyEconomicEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FamilyEconomicEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ClassLibraryEF", "MainWindow.WcfDataServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MainWindow.WcfDataServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ClassLibraryEF.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CurrentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CurrentPrice> CurrentPrices
        {
            get
            {
                if ((this._CurrentPrices == null))
                {
                    this._CurrentPrices = base.CreateQuery<CurrentPrice>("CurrentPrices");
                }
                return this._CurrentPrices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CurrentPrice> _CurrentPrices;
        /// <summary>
        /// There are no comments for MonthlyPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MonthlyPrice> MonthlyPrices
        {
            get
            {
                if ((this._MonthlyPrices == null))
                {
                    this._MonthlyPrices = base.CreateQuery<MonthlyPrice>("MonthlyPrices");
                }
                return this._MonthlyPrices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MonthlyPrice> _MonthlyPrices;
        /// <summary>
        /// There are no comments for PermanentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PermanentPrice> PermanentPrices
        {
            get
            {
                if ((this._PermanentPrices == null))
                {
                    this._PermanentPrices = base.CreateQuery<PermanentPrice>("PermanentPrices");
                }
                return this._PermanentPrices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PermanentPrice> _PermanentPrices;
        /// <summary>
        /// There are no comments for UserDatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserData> UserDatas
        {
            get
            {
                if ((this._UserDatas == null))
                {
                    this._UserDatas = base.CreateQuery<UserData>("UserDatas");
                }
                return this._UserDatas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserData> _UserDatas;
        /// <summary>
        /// There are no comments for UserInfoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserInfo> UserInfoes
        {
            get
            {
                if ((this._UserInfoes == null))
                {
                    this._UserInfoes = base.CreateQuery<UserInfo>("UserInfoes");
                }
                return this._UserInfoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserInfo> _UserInfoes;
        /// <summary>
        /// There are no comments for CurrentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCurrentPrices(CurrentPrice currentPrice)
        {
            base.AddObject("CurrentPrices", currentPrice);
        }
        /// <summary>
        /// There are no comments for MonthlyPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMonthlyPrices(MonthlyPrice monthlyPrice)
        {
            base.AddObject("MonthlyPrices", monthlyPrice);
        }
        /// <summary>
        /// There are no comments for PermanentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPermanentPrices(PermanentPrice permanentPrice)
        {
            base.AddObject("PermanentPrices", permanentPrice);
        }
        /// <summary>
        /// There are no comments for UserDatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserDatas(UserData userData)
        {
            base.AddObject("UserDatas", userData);
        }
        /// <summary>
        /// There are no comments for UserInfoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserInfoes(UserInfo userInfo)
        {
            base.AddObject("UserInfoes", userInfo);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"ClassLibraryEF\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\">" +
                "<EntityType Name=\"CurrentPrice\"><Key><PropertyRef Name=\"Id\" /></Key><Property Na" +
                "me=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xm" +
                "lns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Nam" +
                "e=\"Id_monthly_prices\" Type=\"Edm.Int32\" /><Property Name=\"Id_permanent_prices\" Ty" +
                "pe=\"Edm.Int32\" /><Property Name=\"Price\" Type=\"Edm.String\" MaxLength=\"20\" FixedLe" +
                "ngth=\"false\" Unicode=\"true\" /><Property Name=\"Check_box\" Type=\"Edm.Int32\" /><Pro" +
                "perty Name=\"Consideration\" Type=\"Edm.Int32\" /><NavigationProperty Name=\"MonthlyP" +
                "rice\" Relationship=\"ClassLibraryEF.MonthlyPrice_CurrentPrices\" ToRole=\"MonthlyPr" +
                "ice_CurrentPrices_Source\" FromRole=\"MonthlyPrice_CurrentPrices_Target\" /><Naviga" +
                "tionProperty Name=\"PermanentPrice\" Relationship=\"ClassLibraryEF.PermanentPrice_C" +
                "urrentPrices\" ToRole=\"PermanentPrice_CurrentPrices_Source\" FromRole=\"PermanentPr" +
                "ice_CurrentPrices_Target\" /></EntityType><EntityType Name=\"MonthlyPrice\"><Key><P" +
                "ropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ad" +
                "o/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"fa" +
                "lse\" MaxLength=\"100\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Group\"" +
                " Type=\"Edm.String\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Navigati" +
                "onProperty Name=\"CurrentPrices\" Relationship=\"ClassLibraryEF.MonthlyPrice_Curren" +
                "tPrices\" ToRole=\"MonthlyPrice_CurrentPrices_Target\" FromRole=\"MonthlyPrice_Curre" +
                "ntPrices_Source\" /></EntityType><EntityType Name=\"PermanentPrice\"><Key><Property" +
                "Ref Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:S" +
                "toreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/" +
                "02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"100\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Price\" Type=\"" +
                "Edm.String\" Nullable=\"false\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"Group\" Type=\"Edm.String\" MaxLength=\"20\" FixedLength=\"false\" Uni" +
                "code=\"true\" /><NavigationProperty Name=\"CurrentPrices\" Relationship=\"ClassLibrar" +
                "yEF.PermanentPrice_CurrentPrices\" ToRole=\"PermanentPrice_CurrentPrices_Target\" F" +
                "romRole=\"PermanentPrice_CurrentPrices_Source\" /></EntityType><EntityType Name=\"U" +
                "serData\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32" +
                "\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas." +
                "microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.Stri" +
                "ng\" Nullable=\"false\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Proper" +
                "ty Name=\"Value\" Type=\"Edm.String\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /></EntityType><EntityType Name=\"UserInfo\"><Key><PropertyRef Name=\"Id\" /></K" +
                "ey><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPatter" +
                "n=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" " +
                "/><Property Name=\"LoginName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"20\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Mail\" Type=\"Edm.String\" Null" +
                "able=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"Password\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\"" +
                " Unicode=\"true\" /></EntityType><Association Name=\"MonthlyPrice_CurrentPrices\"><E" +
                "nd Type=\"ClassLibraryEF.MonthlyPrice\" Role=\"MonthlyPrice_CurrentPrices_Source\" M" +
                "ultiplicity=\"0..1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"ClassLibraryEF." +
                "CurrentPrice\" Role=\"MonthlyPrice_CurrentPrices_Target\" Multiplicity=\"*\" /><Refer" +
                "entialConstraint><Principal Role=\"MonthlyPrice_CurrentPrices_Source\"><PropertyRe" +
                "f Name=\"Id\" /></Principal><Dependent Role=\"MonthlyPrice_CurrentPrices_Target\"><P" +
                "ropertyRef Name=\"Id_monthly_prices\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation><Association Name=\"PermanentPrice_CurrentPrices\"><End Type=\"ClassLibrary" +
                "EF.PermanentPrice\" Role=\"PermanentPrice_CurrentPrices_Source\" Multiplicity=\"0..1" +
                "\"><OnDelete Action=\"Cascade\" /></End><End Type=\"ClassLibraryEF.CurrentPrice\" Rol" +
                "e=\"PermanentPrice_CurrentPrices_Target\" Multiplicity=\"*\" /><ReferentialConstrain" +
                "t><Principal Role=\"PermanentPrice_CurrentPrices_Source\"><PropertyRef Name=\"Id\" /" +
                "></Principal><Dependent Role=\"PermanentPrice_CurrentPrices_Target\"><PropertyRef " +
                "Name=\"Id_permanent_prices\" /></Dependent></ReferentialConstraint></Association><" +
                "EntityContainer Name=\"FamilyEconomicEntities\" m:IsDefaultEntityContainer=\"true\">" +
                "<EntitySet Name=\"CurrentPrices\" EntityType=\"ClassLibraryEF.CurrentPrice\" /><Enti" +
                "tySet Name=\"MonthlyPrices\" EntityType=\"ClassLibraryEF.MonthlyPrice\" /><EntitySet" +
                " Name=\"PermanentPrices\" EntityType=\"ClassLibraryEF.PermanentPrice\" /><EntitySet " +
                "Name=\"UserDatas\" EntityType=\"ClassLibraryEF.UserData\" /><EntitySet Name=\"UserInf" +
                "oes\" EntityType=\"ClassLibraryEF.UserInfo\" /><AssociationSet Name=\"MonthlyPrice_C" +
                "urrentPrices\" Association=\"ClassLibraryEF.MonthlyPrice_CurrentPrices\"><End Role=" +
                "\"MonthlyPrice_CurrentPrices_Target\" EntitySet=\"CurrentPrices\" /><End Role=\"Month" +
                "lyPrice_CurrentPrices_Source\" EntitySet=\"MonthlyPrices\" /></AssociationSet><Asso" +
                "ciationSet Name=\"PermanentPrice_CurrentPrices\" Association=\"ClassLibraryEF.Perma" +
                "nentPrice_CurrentPrices\"><End Role=\"PermanentPrice_CurrentPrices_Target\" EntityS" +
                "et=\"CurrentPrices\" /><End Role=\"PermanentPrice_CurrentPrices_Source\" EntitySet=\"" +
                "PermanentPrices\" /></AssociationSet></EntityContainer></Schema></edmx:DataServic" +
                "es></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClassLibraryEF.CurrentPrice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CurrentPrices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CurrentPrice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CurrentPrice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CurrentPrice CreateCurrentPrice(int ID)
        {
            CurrentPrice currentPrice = new CurrentPrice();
            currentPrice.Id = ID;
            return currentPrice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Id_monthly_prices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Id_monthly_prices
        {
            get
            {
                return this._Id_monthly_prices;
            }
            set
            {
                this.OnId_monthly_pricesChanging(value);
                this._Id_monthly_prices = value;
                this.OnId_monthly_pricesChanged();
                this.OnPropertyChanged("Id_monthly_prices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Id_monthly_prices;
        partial void OnId_monthly_pricesChanging(global::System.Nullable<int> value);
        partial void OnId_monthly_pricesChanged();
        /// <summary>
        /// There are no comments for Property Id_permanent_prices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Id_permanent_prices
        {
            get
            {
                return this._Id_permanent_prices;
            }
            set
            {
                this.OnId_permanent_pricesChanging(value);
                this._Id_permanent_prices = value;
                this.OnId_permanent_pricesChanged();
                this.OnPropertyChanged("Id_permanent_prices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Id_permanent_prices;
        partial void OnId_permanent_pricesChanging(global::System.Nullable<int> value);
        partial void OnId_permanent_pricesChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Price;
        partial void OnPriceChanging(string value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Check_box in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Check_box
        {
            get
            {
                return this._Check_box;
            }
            set
            {
                this.OnCheck_boxChanging(value);
                this._Check_box = value;
                this.OnCheck_boxChanged();
                this.OnPropertyChanged("Check_box");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Check_box;
        partial void OnCheck_boxChanging(global::System.Nullable<int> value);
        partial void OnCheck_boxChanged();
        /// <summary>
        /// There are no comments for Property Consideration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Consideration
        {
            get
            {
                return this._Consideration;
            }
            set
            {
                this.OnConsiderationChanging(value);
                this._Consideration = value;
                this.OnConsiderationChanged();
                this.OnPropertyChanged("Consideration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Consideration;
        partial void OnConsiderationChanging(global::System.Nullable<int> value);
        partial void OnConsiderationChanged();
        /// <summary>
        /// There are no comments for MonthlyPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MonthlyPrice MonthlyPrice
        {
            get
            {
                return this._MonthlyPrice;
            }
            set
            {
                this._MonthlyPrice = value;
                this.OnPropertyChanged("MonthlyPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MonthlyPrice _MonthlyPrice;
        /// <summary>
        /// There are no comments for PermanentPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PermanentPrice PermanentPrice
        {
            get
            {
                return this._PermanentPrice;
            }
            set
            {
                this._PermanentPrice = value;
                this.OnPropertyChanged("PermanentPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PermanentPrice _PermanentPrice;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClassLibraryEF.MonthlyPrice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MonthlyPrices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MonthlyPrice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MonthlyPrice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MonthlyPrice CreateMonthlyPrice(int ID, string name)
        {
            MonthlyPrice monthlyPrice = new MonthlyPrice();
            monthlyPrice.Id = ID;
            monthlyPrice.Name = name;
            return monthlyPrice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Group;
        partial void OnGroupChanging(string value);
        partial void OnGroupChanged();
        /// <summary>
        /// There are no comments for CurrentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CurrentPrice> CurrentPrices
        {
            get
            {
                return this._CurrentPrices;
            }
            set
            {
                this._CurrentPrices = value;
                this.OnPropertyChanged("CurrentPrices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CurrentPrice> _CurrentPrices = new global::System.Data.Services.Client.DataServiceCollection<CurrentPrice>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClassLibraryEF.PermanentPrice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PermanentPrices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PermanentPrice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PermanentPrice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="price">Initial value of Price.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PermanentPrice CreatePermanentPrice(int ID, string name, string price)
        {
            PermanentPrice permanentPrice = new PermanentPrice();
            permanentPrice.Id = ID;
            permanentPrice.Name = name;
            permanentPrice.Price = price;
            return permanentPrice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Price;
        partial void OnPriceChanging(string value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Group;
        partial void OnGroupChanging(string value);
        partial void OnGroupChanged();
        /// <summary>
        /// There are no comments for CurrentPrices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CurrentPrice> CurrentPrices
        {
            get
            {
                return this._CurrentPrices;
            }
            set
            {
                this._CurrentPrices = value;
                this.OnPropertyChanged("CurrentPrices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CurrentPrice> _CurrentPrices = new global::System.Data.Services.Client.DataServiceCollection<CurrentPrice>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClassLibraryEF.UserData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UserDatas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UserData : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UserData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserData CreateUserData(int ID, string name)
        {
            UserData userData = new UserData();
            userData.Id = ID;
            userData.Name = name;
            return userData;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClassLibraryEF.UserInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UserInfoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UserInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UserInfo object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="loginName">Initial value of LoginName.</param>
        /// <param name="mail">Initial value of Mail.</param>
        /// <param name="password">Initial value of Password.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserInfo CreateUserInfo(int ID, string loginName, string mail, string password)
        {
            UserInfo userInfo = new UserInfo();
            userInfo.Id = ID;
            userInfo.LoginName = loginName;
            userInfo.Mail = mail;
            userInfo.Password = password;
            return userInfo;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property LoginName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LoginName
        {
            get
            {
                return this._LoginName;
            }
            set
            {
                this.OnLoginNameChanging(value);
                this._LoginName = value;
                this.OnLoginNameChanged();
                this.OnPropertyChanged("LoginName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LoginName;
        partial void OnLoginNameChanging(string value);
        partial void OnLoginNameChanged();
        /// <summary>
        /// There are no comments for Property Mail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Mail
        {
            get
            {
                return this._Mail;
            }
            set
            {
                this.OnMailChanging(value);
                this._Mail = value;
                this.OnMailChanged();
                this.OnPropertyChanged("Mail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Mail;
        partial void OnMailChanging(string value);
        partial void OnMailChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
